# Generated by Django 5.0.6 on 2024-07-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('date_of_registration', models.DateField()),
                ('registration_number', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('contact_person', models.CharField(max_length=255)),
                ('departments', models.JSONField()),
                ('number_of_employees', models.IntegerField()),
                ('contact_phone', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('employee_id_number', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('date_started', models.DateField()),
                ('date_left', models.DateField(blank=True, null=True)),
                ('duties', models.TextField()),
            ],
        ),
    ]
