# Generated by Django 5.0.7 on 2024-07-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_employee_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='departments',
            field=models.TextField(),
        ),
    ]
